--\COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants1.csv' CSV HEADER;
--\COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus1.csv' CSV HEADER;
--\COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections1.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-0.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-1.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-2.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-3.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-4.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-5.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-6.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-7.csv' CSV HEADER;
--\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-8.csv' CSV HEADER;
\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-9.csv' CSV HEADER;
\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-10.csv' CSV HEADER;
\COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/split/items-11.csv' CSV HEADER;
