COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants6.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants4.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants24.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants13.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants20.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants25.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants2.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants15.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants17.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants22.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants23.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants3.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants18.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants10.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants12.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants19.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants9.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants1.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants21.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants11.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants7.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants8.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants5.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants14.csv' CSV HEADER;
COPY restaurants (description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/restaurants16.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus6.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus4.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus24.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus13.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus20.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus25.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus2.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus15.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus17.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus22.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus23.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus3.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus18.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus10.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus12.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus19.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus9.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus1.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus21.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus11.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus7.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus8.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus5.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus14.csv' CSV HEADER;
COPY menus (restaurant_id, description, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/menus16.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections6.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections4.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections24.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections13.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections20.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections25.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections2.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections15.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections17.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections22.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections23.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections3.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections18.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections10.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections12.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections19.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections9.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections1.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections21.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections11.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections7.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections8.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections5.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections14.csv' CSV HEADER;
COPY sections (menu_id, title) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/sections16.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items6.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items4.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items24.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items13.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items20.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items25.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items2.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items15.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items17.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items22.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items23.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items3.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items18.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items10.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items12.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items19.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items9.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items1.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items21.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items11.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items7.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items8.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items5.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items14.csv' CSV HEADER;
COPY items (section_id, description, title, price) FROM '/home/jordan/HackReactor/SDC/menu-service/database/datasets/items16.csv' CSV HEADER;
